In [1]:
import numpy as np
from datetime import datetime


In [2]:
arreglo = np.array((1,2,3))
arreglo

array([1, 2, 3])

In [3]:
type(arreglo)

numpy.ndarray

In [4]:
for i in arreglo:
    print('valor: {}, tipo:{}'.format(i,type(i)))

valor: 1, tipo:<class 'numpy.int32'>
valor: 2, tipo:<class 'numpy.int32'>
valor: 3, tipo:<class 'numpy.int32'>


In [5]:
arreglo = np.array((1,2,3))
print(arreglo)
print(type(arreglo))
for i in arreglo:
    print('valor: {}, tipo:{}'.format(i,type(i)))

[1 2 3]
<class 'numpy.ndarray'>
valor: 1, tipo:<class 'numpy.int32'>
valor: 2, tipo:<class 'numpy.int32'>
valor: 3, tipo:<class 'numpy.int32'>


In [6]:
arreglo = np.array(['d', 3 , (12, 6, True)], dtype=object)
for i in arreglo:
    print('valor: {}, tipo:{}'.format(i,type(i)))

valor: d, tipo:<class 'str'>
valor: 3, tipo:<class 'int'>
valor: (12, 6, True), tipo:<class 'tuple'>


### El atributo ```shape```.

Los arreglos cuentan con el atributo ```shape```, el cual describe el número de elementos que contiene cada dimensión del arreglo.

El valor de ```shape``` es un objeto tipo tuple que contiene una sucesión de números.

```
(<n1>, <n2>, <n3> ... <nm>)
```

* Donde ```<n1>``` corresponde al número de elementos en la primera dimensión,  ```<n2>``` corresponde al número de elementos en la segunda dimensión y así sucesivamente hasta ```<nm>``` , la cual corrersponde al número de elementos de la dimensión ```m```.


In [7]:
arreglo = np.array((1,2,3))
print(arreglo.ndim) #NUmero de dimesiones
print(arreglo.shape) #Numero de elementos en cada dimension
print(arreglo.size) #Numero total de elementos en el arreglo

1
(3,)
3


In [8]:
#Arreglo bidimensional
arreglo = np.array([[1, 2, 3],
                    [4, 5, 6]])
print(arreglo.ndim) #NUmero de dimesiones
print(arreglo.shape) #Numero de elementos en cada dimension
print(arreglo.size) #Numero total de elementos en el arreglo

2
(2, 3)
6


In [9]:
#Arreglo tridimesional
arreglo = np.array([[[1, 2], [3, 4]],
                    [[5, 6], [7, 8]]])
print(arreglo.ndim) #Numero de dimesiones
print(arreglo.shape) #Numero de elementos en cada dimension
print(arreglo.size) #Numero total de elementos en el arreglo

3
(2, 2, 2)
8


In [10]:
np.array(((1, 2), (3, 4)))
#np.array(((1, 2), (3, 4))).shape

array([[1, 2],
       [3, 4]])

In [11]:
#Tipo por default
np.array(((1, 2), (3, 4))).dtype

dtype('int32')

In [12]:
np.array(((-1, 2), (3, 4)), dtype = np.uint8)

array([[255,   2],
       [  3,   4]], dtype=uint8)

In [13]:
np.array(((-1, 2), (3, 4)), dtype = np.uint64)

array([[18446744073709551615,                    2],
       [                   3,                    4]], dtype=uint64)

In [14]:
#Tipos complejos 
complejo=np.array([[25.6j, 11.24],
                [-21.890-15702174.43j, 0]])
print(complejo)
print(complejo.dtype)

[[  0.  +2.56000000e+01j  11.24+0.00000000e+00j]
 [-21.89-1.57021744e+07j   0.  +0.00000000e+00j]]
complex128


In [15]:
np.array(((1,'Hola'),(False,0)))

array([['1', 'Hola'],
       ['False', '0']], dtype='<U11')

In [16]:
np.array(((1,'Hola'),(False,0)), dtype = np.bool_)

array([[ True,  True],
       [False, False]])

In [17]:
#Tipo cadena
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']))

array([['Hugo', 'Paco'],
       ['Luis Ignacio', 'Donald']], dtype='<U12')

In [18]:
np.array((['Hugo', 'Paco'],['Luis Ignacio', 'Donald']), dtype = np.string_)


array([[b'Hugo', b'Paco'],
       [b'Luis Ignacio', b'Donald']], dtype='|S12')

In [19]:
#Trabajo con fechas
fechas = np.array([[np.datetime64("2019-08-25T23:59:45.231"), 
                   np.datetime64("2020-07-23")],
                   [np.datetime64(datetime(year=2018, month=12, day=22)),
                   np.datetime64("2019-03-01T11:25")]])
fechas

array([['2019-08-25T23:59:45.231000', '2020-07-23T00:00:00.000000'],
       ['2018-12-22T00:00:00.000000', '2019-03-01T11:25:00.000000']],
      dtype='datetime64[us]')

In [20]:
#deltatiem los segundos en un lapso de tiempo
np.datetime64(datetime.now()) - fechas

array([[ 89716002309591,  61031187540591],
       [111056787540591, 105054087540591]], dtype='timedelta64[us]')

In [21]:
a1 = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

a2 = np.array([[[10, 20], [30, 40]],
                [[50, 60], [70, 80]]])


a2 = np.array((100,200))

print(a1+a2)
print('')
print(a1*101)
print('')
print(a1*a2)

[[[101 202]
  [103 204]]

 [[105 206]
  [107 208]]]

[[[101 202]
  [303 404]]

 [[505 606]
  [707 808]]]

[[[ 100  400]
  [ 300  800]]

 [[ 500 1200]
  [ 700 1600]]]


In [22]:
# ndarray regresa un arreglo con valores no definidos cercanos a 0
np.ndarray((2,2), dtype=float)

array([[8.48798316e-312, 1.69759663e-311],
       [2.54639495e-311, 3.39519327e-311]])

In [23]:
np.ndarray((2,2), dtype='>U10')

array([['', ''],
       ['', '']], dtype='>U10')

In [24]:
np.ndarray((2,5,3,6))

array([[[[9.24410625e-312, 9.24411156e-312, 9.24416256e-312,
          9.24411152e-312, 0.00000000e+000,             nan],
         [            nan, 0.00000000e+000, 6.92541988e-255,
          0.00000000e+000, 4.44659081e-323, 9.24416256e-312],
         [9.24411153e-312,             nan, 0.00000000e+000,
                      nan, 0.00000000e+000, 9.23068169e-312]],

        [[3.55727265e-322, 5.43472210e-323, 9.24416256e-312,
          9.24411154e-312, 9.88131292e-324, 4.94065646e-323],
         [            nan, 0.00000000e+000, 9.23068169e-312,
          7.11454530e-322, 5.43472210e-323, 9.24416256e-312],
         [9.24411154e-312,             nan, 1.28457068e-322,
                      nan, 0.00000000e+000, 4.94065646e-324]],

        [[1.06718180e-321, 5.43472210e-323, 9.24416256e-312,
          9.24411154e-312, 4.94065646e-323, 1.28457068e-322],
         [            nan, 0.00000000e+000, 9.23068169e-312,
          1.42290906e-321, 5.43472210e-323, 9.24416256e-312],
         [9.

In [25]:
np.ones((2,5,3,6))

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],


In [26]:
np.zeros((2,5,3,6))

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],


In [27]:
np.zeros((2,2,2),dtype=bool)

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [28]:
np.ones((2,2,2),dtype=bool)

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [29]:
#empty genera arreglos con valores no inicializados
np.empty((2,2,2), dtype = np.int8)

array([[[48,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0]]], dtype=int8)

In [30]:
# arange genera un arreglo unidimensional con valores enteros en un rango
np.arange(6,21)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
# arange(limite inferior, limite superior, salto)
np.arange(-30,10,4)

array([-30, -26, -22, -18, -14, -10,  -6,  -2,   2,   6])

In [32]:
#linspace genera un arreglo unidimensional con una secuencia lineal de valores dentro de un rango
np.linspace(0,8)

array([0.        , 0.16326531, 0.32653061, 0.48979592, 0.65306122,
       0.81632653, 0.97959184, 1.14285714, 1.30612245, 1.46938776,
       1.63265306, 1.79591837, 1.95918367, 2.12244898, 2.28571429,
       2.44897959, 2.6122449 , 2.7755102 , 2.93877551, 3.10204082,
       3.26530612, 3.42857143, 3.59183673, 3.75510204, 3.91836735,
       4.08163265, 4.24489796, 4.40816327, 4.57142857, 4.73469388,
       4.89795918, 5.06122449, 5.2244898 , 5.3877551 , 5.55102041,
       5.71428571, 5.87755102, 6.04081633, 6.20408163, 6.36734694,
       6.53061224, 6.69387755, 6.85714286, 7.02040816, 7.18367347,
       7.34693878, 7.51020408, 7.67346939, 7.83673469, 8.        ])

In [33]:
np.linspace(0,8, num=100)

array([0.        , 0.08080808, 0.16161616, 0.24242424, 0.32323232,
       0.4040404 , 0.48484848, 0.56565657, 0.64646465, 0.72727273,
       0.80808081, 0.88888889, 0.96969697, 1.05050505, 1.13131313,
       1.21212121, 1.29292929, 1.37373737, 1.45454545, 1.53535354,
       1.61616162, 1.6969697 , 1.77777778, 1.85858586, 1.93939394,
       2.02020202, 2.1010101 , 2.18181818, 2.26262626, 2.34343434,
       2.42424242, 2.50505051, 2.58585859, 2.66666667, 2.74747475,
       2.82828283, 2.90909091, 2.98989899, 3.07070707, 3.15151515,
       3.23232323, 3.31313131, 3.39393939, 3.47474747, 3.55555556,
       3.63636364, 3.71717172, 3.7979798 , 3.87878788, 3.95959596,
       4.04040404, 4.12121212, 4.2020202 , 4.28282828, 4.36363636,
       4.44444444, 4.52525253, 4.60606061, 4.68686869, 4.76767677,
       4.84848485, 4.92929293, 5.01010101, 5.09090909, 5.17171717,
       5.25252525, 5.33333333, 5.41414141, 5.49494949, 5.57575758,
       5.65656566, 5.73737374, 5.81818182, 5.8989899 , 5.97979

In [34]:
arreglo = np.linspace(0,8, num=100)
np.savetxt('arreglo.txt', arreglo)

In [35]:
#Escribir en un archivo binario
np.save('arreglo', arreglo)

In [36]:
#Leer archivo
arreglo2 = np.loadtxt('arreglo.txt')
arreglo2

array([0.        , 0.08080808, 0.16161616, 0.24242424, 0.32323232,
       0.4040404 , 0.48484848, 0.56565657, 0.64646465, 0.72727273,
       0.80808081, 0.88888889, 0.96969697, 1.05050505, 1.13131313,
       1.21212121, 1.29292929, 1.37373737, 1.45454545, 1.53535354,
       1.61616162, 1.6969697 , 1.77777778, 1.85858586, 1.93939394,
       2.02020202, 2.1010101 , 2.18181818, 2.26262626, 2.34343434,
       2.42424242, 2.50505051, 2.58585859, 2.66666667, 2.74747475,
       2.82828283, 2.90909091, 2.98989899, 3.07070707, 3.15151515,
       3.23232323, 3.31313131, 3.39393939, 3.47474747, 3.55555556,
       3.63636364, 3.71717172, 3.7979798 , 3.87878788, 3.95959596,
       4.04040404, 4.12121212, 4.2020202 , 4.28282828, 4.36363636,
       4.44444444, 4.52525253, 4.60606061, 4.68686869, 4.76767677,
       4.84848485, 4.92929293, 5.01010101, 5.09090909, 5.17171717,
       5.25252525, 5.33333333, 5.41414141, 5.49494949, 5.57575758,
       5.65656566, 5.73737374, 5.81818182, 5.8989899 , 5.97979

In [37]:
%ls

 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: A856-E4AA

 Directorio de C:\Users\Mario Alberto\Python_Pandas

28/06/2022  11:02 a. m.    <DIR>          .
28/06/2022  11:02 a. m.    <DIR>          ..
28/06/2022  09:10 a. m.    <DIR>          .ipynb_checkpoints
28/01/2022  01:16 p. m.           118,573 07PandasLimpiezaDatos.ipynb
28/01/2022  01:28 p. m.            17,119 08PandasAgrupamientos.ipynb
26/01/2022  11:27 a. m.               520 a1
26/01/2022  11:38 a. m.               520 a1.txt
28/06/2022  10:20 a. m.               160 a1.txt.npy
26/01/2022  11:45 a. m.               160 a3.npy
26/01/2022  11:29 a. m.               102 a3.txt
29/06/2022  09:06 a. m.               928 arreglo.npy
29/06/2022  09:06 a. m.             2,600 arreglo.txt
28/06/2022  10:27 a. m.               546 arreglos.npz
27/01/2022  11:52 p. m.            26,229 Ejercicio4.ipynb
30/01/2022  02:38 a. m.            54,095 EjercicioFinal.ipynb
27/01/2022  01:37 p. m.           

In [38]:
np.save('a1.txt',a1)

In [39]:
np.load('a1.txt.npy')

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
np.savez('arreglos',a1,a2)

In [41]:
cargados = np.load('arreglos.npz')
cargados

In [42]:
cargados['arr_0']

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [43]:
with cargados as arr:
    for i in arr:
        print(i, arr[i])

arr_0 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
arr_1 [100 200]


In [44]:
with np.load('arreglos.npz') as arr:
    ac2 = arr['arr_1']
ac2

array([100, 200])

# Operaciones básicas con arreglos.
La siguiente tabla ejemplifica la conformación de las Equipos en una semana dada.

||Equipo 1| Equipo 2|
|:--:|:---:|:---:|
|**Lunes**|Lilia, Antonio, Ricardo|Alonso, Jorge, Salvador|
|**Martes**|Mariana, Julian, Ricardo|Arturo, Ramy, Esteban|
|**Miércoles**|Arturo, Ricardo, Lucio|Jorge, Marco, Lilia|
|**Jueves**|Alonso, Julian, Salvador|Ricardo, Jorge, Esteban|
|**Viernes**|Lucio, Ramy, Joaquín|Ricardo, Marco, Lilia|


In [45]:
# Operaciones básicas con arreglos.
equipos = np.array([[['Lilia', 'Antonio', 'Ricardo'], ['Alonso', 'Jorge', 'Salvador']],
                    [['Mariana', 'Julian', 'Ricardo'], ['Arturo', 'Ramy', 'Esteban']],
                    [['Arturo', 'Ricardo', 'Lucio'], ['Jorge', 'Marco', 'Lilia']],
                    [['Alonso', 'Julian', 'Salvador'], ['Ricardo', 'Jorge', 'Esteban']],
                    [['Lucio', 'Ramy', 'Joaquín'], ['Ricardo', 'Marco', 'Lilia']]])


In [46]:
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Lucio', 'Ramy', 'Joaquín'],
        ['Ricardo', 'Marco', 'Lilia']]], dtype='<U8')

In [47]:
print(equipos.ndim)
print(equipos.shape)
print(equipos.size)

3
(5, 2, 3)
30


In [48]:
#Slices de arreglos
equipos[1:3]

array([[['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']]], dtype='<U8')

In [49]:
equipos[1:3].shape

(2, 2, 3)

In [50]:
#Ver el equipo 2 de los dias martes y miercoles de la semana
equipos[1:3, 1]

array([['Arturo', 'Ramy', 'Esteban'],
       ['Jorge', 'Marco', 'Lilia']], dtype='<U8')

In [51]:
equipos[1:3, 1].shape

(2, 3)

In [52]:
#Ver los 2 primeros integrantes del equipo 2 de los dias martes y miercoles
equipos[1:3,1,0:2]

array([['Arturo', 'Ramy'],
       ['Jorge', 'Marco']], dtype='<U8')

In [53]:
equipos[1:3,1,0:2].shape

(2, 2)

In [54]:
#Ver el tercer integrante del equipo 1 en todos los dias
equipos[:,0,2:3]

array([['Ricardo'],
       ['Ricardo'],
       ['Lucio'],
       ['Salvador'],
       ['Joaquín']], dtype='<U8')

In [55]:
equipos[4, 1, 2]

'Lilia'

In [56]:
print(type(equipos[4,1,2]))
print(equipos[4,1,2].shape)
print(equipos[4,1,2].size)

<class 'numpy.str_'>
()
1


# Remplazos
|Equipo 1| Equipo 2|
:---:|:---:|
|Paulina, Rigo, Paul|Kenia, Miguel, Carlos|


In [57]:
remplazos = np.array([['Paulina', 'Rigo', 'Paul'], 
               ['Kenia', 'Miguel', 'Carlos']])
remplazos

array([['Paulina', 'Rigo', 'Paul'],
       ['Kenia', 'Miguel', 'Carlos']], dtype='<U7')

In [58]:
remplazos.shape

(2, 3)

In [59]:
equipos[4]

array([['Lucio', 'Ramy', 'Joaquín'],
       ['Ricardo', 'Marco', 'Lilia']], dtype='<U8')

In [60]:
equipos[4].shape

(2, 3)

In [61]:
#Cambiar elementos de un arreglo
equipos[4] = remplazos
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Paulina', 'Rigo', 'Paul'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')

In [63]:
#Cambiar los elementos de un arreglo
equipos[2,0, 0:2] = ['Julio','Ernesto']
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Julio', 'Ernesto', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Paulina', 'Rigo', 'Paul'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')

In [65]:
#Cambiar un solo elemento
equipos[3,1,2] = 'Esmeralda'
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Julio', 'Ernesto', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esmerald']],

       [['Paulina', 'Rigo', 'Paul'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')

In [72]:
#Es posible identificar elementos de una dimension usando arreglos para indices
idx_1 = np.array([2,0,3])
print(idx_1)
print(equipos[idx_1].shape)

[2 0 3]
(3, 2, 3)


In [71]:
idx_2 = np.array([[0,3], [1,4]])
print(idx_2)
print(equipos[idx_2])

[[0 3]
 [1 4]]
[[[['Lilia' 'Antonio' 'Ricardo']
   ['Alonso' 'Jorge' 'Salvador']]

  [['Alonso' 'Julian' 'Salvador']
   ['Ricardo' 'Jorge' 'Esmerald']]]


 [[['Mariana' 'Julian' 'Ricardo']
   ['Arturo' 'Ramy' 'Esteban']]

  [['Paulina' 'Rigo' 'Paul']
   ['Kenia' 'Miguel' 'Carlos']]]]


In [74]:
# Uso de multiples arreglos como indices
idx_x = np.array([0,2]) #Lunes y miercoles
idx_y = np.array([0,1]) #Equipo 1 y 2
equipos[idx_x,idx_y]

array([['Lilia', 'Antonio', 'Ricardo'],
       ['Jorge', 'Marco', 'Lilia']], dtype='<U8')

# 'Brodcasting'

In [75]:
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Julio', 'Ernesto', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esmerald']],

       [['Paulina', 'Rigo', 'Paul'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')

In [76]:
# Un mismo valor para todos los elementos
equipos[4,0] = 'Fabian'
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Julio', 'Ernesto', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esmerald']],

       [['Fabian', 'Fabian', 'Fabian'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')

In [81]:
#Un mismo arreglo para todos los elementos de la dimension
equipos[2] = np.array(['Hugo','Paco','Luis'])
equipos[2].shape
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Hugo', 'Paco', 'Luis'],
        ['Hugo', 'Paco', 'Luis']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esmerald']],

       [['Fabian', 'Fabian', 'Fabian'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')