In [1]:
import numpy as np

In [4]:
m1 = np.array([[1,2,3],
              [10,11,12],
              [-5,-8,-14]])
print(m1)
print(m1.shape)

[[  1   2   3]
 [ 10  11  12]
 [ -5  -8 -14]]
(3, 3)


In [3]:
# Las operaciones aritmeticas se aplican a todos los elementos de la matriz
m1*200

array([[  200,   400,   600],
       [ 2000,  2200,  2400],
       [-1000, -1600, -2800]])

In [6]:
#Aplicar la operacion a un elemento
m1[1] + 15

array([25, 26, 27])

In [7]:
m1 / 5.45

array([[ 0.18348624,  0.36697248,  0.55045872],
       [ 1.83486239,  2.01834862,  2.20183486],
       [-0.91743119, -1.46788991, -2.56880734]])

In [8]:
#Usar operadores logicos por brodcasting
m1 > 1

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [9]:
m2 = np.array([1,2,3])
m3 = np.array([[2],[4],[6]])

print(m2)
print(m2.shape)

print(m3)
print(m3.shape)

[1 2 3]
(3,)
[[2]
 [4]
 [6]]
(3, 1)


In [10]:
m1*m2

array([[  1,   4,   9],
       [ 10,  22,  36],
       [ -5, -16, -42]])

In [11]:
m1/m3

array([[ 0.5       ,  1.        ,  1.5       ],
       [ 2.5       ,  2.75      ,  3.        ],
       [-0.83333333, -1.33333333, -2.33333333]])

In [12]:
m4 = m1 +20
m4

array([[21, 22, 23],
       [30, 31, 32],
       [15, 12,  6]])

In [13]:
m1 * m4

array([[ 21,  44,  69],
       [300, 341, 384],
       [-75, -96, -84]])

In [14]:
#Generar arreglos con valores aleatorios 
np.random.rand(2,2,2)

array([[[0.34474509, 0.61443406],
        [0.82470774, 0.2834516 ]],

       [[0.03170772, 0.31873262],
        [0.47417827, 0.8425288 ]]])

In [15]:
# randit genera valores enteros aleatorios entre un rango
np.random.randint(1,255,(2,2,2))

array([[[228, 218],
        [207, 152]],

       [[187, 219],
        [ 20, 244]]])

In [16]:
np.random.randint(0,256,(3,2,4))

array([[[  4, 184,  52,  85],
        [200, 110,  58, 146]],

       [[155,  84, 226, 191],
        [205, 114, 170,  34]],

       [[ 78,  26, 150,  18],
        [ 42, 146, 126,  24]]])

In [17]:
numeros = np.array([[2.43, -3, 48.9999, -5.61],
                   [np.inf, -np.inf, np.inf, np.inf],
                   [np.nan, 17.78, 12, 22]])
numeros

array([[ 2.43  , -3.    , 48.9999, -5.61  ],
       [    inf,    -inf,     inf,     inf],
       [    nan, 17.78  , 12.    , 22.    ]])

In [18]:
#Funciones de valor
print(np.abs(numeros))
print(np.floor(numeros))
print(np.ceil(numeros))
print(np.round(numeros))

[[ 2.43    3.     48.9999  5.61  ]
 [    inf     inf     inf     inf]
 [    nan 17.78   12.     22.    ]]
[[  2.  -3.  48.  -6.]
 [ inf -inf  inf  inf]
 [ nan  17.  12.  22.]]
[[  3.  -3.  49.  -5.]
 [ inf -inf  inf  inf]
 [ nan  18.  12.  22.]]
[[  2.  -3.  49.  -6.]
 [ inf -inf  inf  inf]
 [ nan  18.  12.  22.]]


In [22]:
#Funciones de la evaluacion de arreglos
print(np.isfinite(numeros))
print(np.isnan(numeros))
print(np.isreal(numeros))
print(np.isscalar(numeros))

[[ True  True  True  True]
 [False False False False]
 [False  True  True  True]]
[[False False False False]
 [False False False False]
 [ True False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
False


## Funciones estadísticas.

* ```np.amax()```
* ```np amin()```
* ```np.argmax()```
* ```np.argmin()```
* ```np.average()```
* ```np.correlate()```
* ```np.corrcoef()```
* ```np.count_nonzero()```
* ```np.cov()```
* ```np.cumprod()```
* ```np.cumsum()```
* ```np.histogram()```
* ```np.histogram2d()```
* ```np.histogram_bin_edges()```
* ```np.histogramdd()```
* ```np.max()```
* ```np.mean()```
* ```np.median()```
* ```np.min()```
* ```np.nanargmax()```
* ```np.nanargmin()```
* ```np.nancumprod()```
* ```np.nancumsum()```
* ```np.nanmax()```
* ```np.nanmean()```
* ```np.nanmedian()```
* ```np.nanmin()```
* ```np.nanpercentile()```
* ```np.nanquantile()```
* ```np.nanstd()```
* ```np.nansum()```
* ```np.nanvar()```
* ```np.percentile()```
* ```np.quantile()```
* ```np.std()```
* ```np.var()```


In [25]:
numeros = np.random.randint(0,256,(3,2,4))
numeros

array([[[161, 126,  32, 182],
        [ 44,  48, 149, 200]],

       [[209, 127, 168, 176],
        [ 56,   2, 225, 108]],

       [[ 91,  92,  60, 139],
        [171,  17,  36, 193]]])

## Funciones de valor
* ```np.abs()```
* ```np.around()```
* ```np.ceil()```
* ```np.exp()```
* ```np.exp2()```
* ```np.fabs()```
* ```np.fix()```
* ```np.floor()```
* ```np.log()```
* ```np.log10()```
* ```np.log1p()```
* ```np.log2()```
* ```np.logaddexp()```
* ```np.logaddexp2()```
* ```np.round()```


In [28]:
print(np.max(numeros))
print(np.mean(numeros))
print(np.min(numeros))
print(np.median(numeros))

225
117.16666666666667
2
126.5


In [27]:
print(np.nanmax(numeros))
print(np.nanmean(numeros))
print(np.nanmin(numeros))
print(np.nanmedian(numeros))

225
117.16666666666667
2
126.5


In [29]:
np.histogram(numeros)

(array([2, 3, 3, 1, 2, 2, 2, 4, 3, 2], dtype=int64),
 array([  2. ,  24.3,  46.6,  68.9,  91.2, 113.5, 135.8, 158.1, 180.4,
        202.7, 225. ]))

In [36]:
#Copia y ordenamiento
numeros1 = numeros #Alias de un arreglo
numeros1 = np.copy(numeros)#Copia de arreglo
numeros

array([[[161, 126,  32, 182],
        [ 44,  48, 149, 200]],

       [[209, 127, 168, 176],
        [ 56,   2, 225, 108]],

       [[ 91,  92,  60, 139],
        [171,  17,  36, 193]]])

In [32]:
numeros1.sort()
numeros1

array([[[ 32, 126, 161, 182],
        [ 44,  48, 149, 200]],

       [[127, 168, 176, 209],
        [  2,  56, 108, 225]],

       [[ 60,  91,  92, 139],
        [ 17,  36, 171, 193]]])

In [40]:
numeros1.sort(axis=2)
numeros1

array([[[ 32, 126, 161, 182],
        [ 44,  48, 149, 200]],

       [[127, 168, 176, 209],
        [  2,  56, 108, 225]],

       [[ 60,  91,  92, 139],
        [ 17,  36, 171, 193]]])

In [38]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

print(a)
print(b)

print(np.add(a,b))

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [5 7 9]]


In [39]:
#Suma total de los elementos
b.sum()

21

In [41]:
# Raiz cuadrada
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [42]:
# Crear un arreglo con los resultados de la comparacion logica
c=b <=4
c

array([[ True,  True,  True],
       [ True, False, False]])